### PR TITLE
Fix missing context for QgsMapLayerRenderer subclasses

### PR DESCRIPTION
**Pull request by domi4484**

### CODE REVIEW

**Comment by 3nids** [comment]
What is the reason to switch to a pointer? Looking in QGIS source code shows mainly the use of a const ref.

**Comment by domi4484** [comment]
@3nids done thanks

**Comment by 3nids** [comment]
Thanks. Sorry, I misread, I would follow QGIS API and use the same signature in the subclass. So let's go with your first commit, it's good!

**Comment by domi4484** [comment]
In the end in qgis it's the same, they change the signature in subclasses. So I'll keep the second commit to stay more close to that

**Pull request merged**
