### PR TITLE
Install the icon in the right place

### PR DESCRIPTION
**Pull request by aleixpol**
As it is it would create a kadas.org directory and install there.

### CODE REVIEW

**Comment by manisandro** [comment]
I'm confused about this one, will this rename the icon to `kadas.org`?

**Comment by aleixpol** [comment]
Yes, my bad. I fixed it here, should be good now.

**Comment by manisandro** [comment]
I still see the `RENAME kadas.org`?

**Comment by manisandro** [comment]
Thanks!

**Pull request merged**
