### PR TITLE
Add QCA and QtKeychain to CMake

### PR DESCRIPTION
**Pull request by domi4484**
@m-kuhn I don't get why last time I was able to build without that, so maybe I have another issue... The INCLUDE_DIRECTORIES are probably not at the right place?

### CODE REVIEW

**Comment by domi4484** [comment]
@m-kuhn  Ouch I see now that you removed some of that stuff in #52

**Comment by m-kuhn** [comment]
@domi4484 what were your build errors?

**Comment by domi4484** [comment]
> @domi4484 what were your build errors?

Includes of QtCrypto and keychain.h

And QtSerialport as well, i have disabled It for the moment

**Comment by m-kuhn** [comment]
The situation is not ideal at the moment, as QGIS doesn't generate a config file to export its dependencies.
I hope we will one day have that, as this would make everything a lot easier. To be prepared I would like to isolate all additions for transient dependencies in FindQGIS.cmake as done in #54. Does that work for you?

**Pull request closed without merging**
